# Generated by Django 5.0.1 on 2024-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=50)),
                ('cat', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Sport', 'Sport'), ('Racing', 'Racing'), ('Survival', 'Survival'), ('Platform', 'Platform')], max_length=50)),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
