# Generated by Django 5.0.1 on 2024-03-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images'),
        ),
    ]
